apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx-server
        image: ramaraja/webserver:1.0
        imagePullPolicy: IfNotPresent

  replicas: 2
  selector:
    matchLabels:
      app: webserver

---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP

  selector:
    app: webserver