apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: dev
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: user-config
      ports:
        - name: web-port-1
          containerPort: 80