apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
    - name: webapp-container
      image: 883669142223.dkr.ecr.ap-south-1.amazonaws.com/myorg:latest
