apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
    - name: webserver
      image: ramaraja/webserver
      ports:
        - name: web-port-1
          containerPort: 80

      volumeMounts:
        - mountPath: "/web"
          name: pv-test

  volumes:
    - name: pv-test
      persistentVolumeClaim:
        claimName: pvtest-claim-1
