apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvtest-claim-1
  labels:
    app: webserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi