apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-toleration
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "team"
    operator: "Equal"
    value: "test"
    effect: "NoSchedule"



# kubectl taint nodes minikube team=ml:NoSchedule

# kubectl taint nodes <node-name> <key>- 

